Allow specifying different word lists via an environment variable

diff --git a/genhost b/genhost
--- a/genhost
+++ b/genhost
@@ -4,8 +4,19 @@
 # genhost - generate unused hostnames by randomly picking from a word list
 #
 
-readonly wordlist=$(dirname $0)/wordlist
+# script path variables
+readonly script=$(realpath $0)
+readonly script_name=$(basename $script)
+readonly script_dir=$(dirname $script)
+
+readonly wordlist=${GENHOST_WORDLIST:-wordlist}
 readonly domain=${GENHOST_DOMAIN:-example.com}
+
+# validate path to word list file
+if [[ "$wordlist" == *".."* ]] || [ "$(basename $wordlist)" == "$script_name" ]; then
+    printf 'genhost: invalid word list file: %s\n' $wordlist
+    exit 1
+fi
 
 # http://mywiki.wooledge.org/BashFAQ/026
 
